<a href="https://colab.research.google.com/github/rpsing2006-maker/sample_repo/blob/main/Python_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy introduction

In [3]:
import numpy as np

In [4]:
a = [1,2,3]
b = np.array(a)

In [6]:
b

array([1, 2, 3])

In [5]:
type(b)

numpy.ndarray

In [7]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
print("total rows and columns :", b.size)
print("Size is:", b.size)

total rows and columns : 9
Size is: 9


In [12]:
a = [1,2,3]
print(a*3)

b = np.array(a)
print(b*3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


In [ ]:
#functions in numpy

In [ ]:
# (1). Zeros() --- arrays of zeros

In [16]:
a = np.zeros(3)
print(a)
print()

a = np.zeros((2,3))
print(a)

[0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# (2). Ones() --- array of ones

In [18]:
a = np.ones(3)
a

array([1., 1., 1.])

In [19]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# (3). eye() --- all diagonals will be 1

In [20]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# (4). Diag() --- Custom values in diagonal position

In [22]:
a = np.diag([1,2,34,5,2])
a

array([[ 1,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0],
       [ 0,  0, 34,  0,  0],
       [ 0,  0,  0,  5,  0],
       [ 0,  0,  0,  0,  2]])

In [ ]:
#(5). random module